"""Descriptions of gym equipment the on-device model matches a photograph against.

Keys match MachineGuide.id in core/.../workout/Equipment.kt. Each machine has two or three
phrasings; the app scores a photo against the best-matching one per machine. Regenerate the
embeddings with embed_prompts.py after any change.
"""

EQUIPMENT_PROMPTS = {
    "lat_pulldown": ["a photo of a lat pulldown machine in a gym",
                     "a cable lat pulldown station with a long bar hanging overhead and a knee pad"],
    "cable_row": ["a photo of a seated cable row machine in a gym",
                  "a low pulley rowing station with a bench and foot platform"],
    "cable_station": ["a photo of a cable crossover machine in a gym",
                      "a dual adjustable pulley cable station with handles"],
    "leg_press": ["a photo of a leg press machine in a gym",
                  "an angled sled leg press machine with a large foot platform"],
    "leg_extension": ["a photo of a leg extension machine in a gym",
                      "a seated quadriceps extension machine with an ankle roller pad"],
    "leg_curl": ["a photo of a lying leg curl machine in a gym",
                 "a hamstring curl machine with a padded bench and roller"],
    "smith_machine": ["a photo of a smith machine in a gym",
                      "a barbell fixed on vertical guide rails in a steel frame"],
    "squat_rack": ["a photo of a squat rack with a barbell in a gym",
                   "a power rack cage with a loaded barbell on j-hooks"],
    "bench_press": ["a photo of a flat bench press station with a barbell",
                    "a weight bench with a barbell resting on uprights"],
    "adjustable_bench": ["a photo of an adjustable incline weight bench",
                         "an inclined gym bench with dumbbells beside it"],
    "dumbbells": ["a photo of a dumbbell rack in a gym",
                  "rows of dumbbells on a rack"],
    "chest_press_machine": ["a photo of a seated chest press machine in a gym",
                            "a plate loaded chest press machine with handles at chest height"],
    "pec_deck": ["a photo of a pec deck fly machine in a gym",
                 "a seated chest fly machine with two swinging arms"],
    "shoulder_press_machine": ["a photo of a seated shoulder press machine in a gym",
                               "an overhead press machine with handles above the seat"],
    "pullup_station": ["a photo of an assisted pull-up machine in a gym",
                       "a pull-up bar station for chin ups"],
    "dip_station": ["a photo of a dip station with parallel bars",
                    "parallel dip bars in a gym"],
    "hack_squat": ["a photo of a hack squat machine in a gym",
                   "an angled squat machine with shoulder pads on a sliding sled"],
    "hip_thrust": ["a photo of a hip thrust machine in a gym",
                   "a glute bridge machine with a padded belt over the hips"],
    "calf_raise_standing": ["a photo of a standing calf raise machine",
                            "a calf raise machine with shoulder pads and a small step"],
    "calf_raise_seated": ["a photo of a seated calf raise machine",
                          "a seated machine with a knee pad and a foot platform for calves"],
    "hip_abductor": ["a photo of a hip abductor machine in a gym",
                     "a seated inner and outer thigh machine with leg pads"],
    "back_extension": ["a photo of a back extension bench, a roman chair",
                       "a hyperextension bench in a gym"],
    "preacher_curl": ["a photo of a preacher curl bench",
                      "a bicep curl bench with an angled arm pad"],
    "kettlebell": ["a photo of a kettlebell on a gym floor",
                   "cast iron kettlebells"],
    "tbar_row": ["a photo of a chest supported t-bar row machine",
                 "a t-bar row machine with a chest pad and handles"],
    "captains_chair": ["a photo of a captain's chair vertical knee raise station",
                       "an ab station with arm rests and a back pad for leg raises"],
    "battle_ropes": ["a photo of battle ropes in a gym",
                     "two thick heavy ropes anchored to the wall on a gym floor"],
    "treadmill": ["a photo of a treadmill in a gym",
                  "a running machine with a moving belt and a console"],
    "stationary_bike": ["a photo of an exercise bike in a gym",
                        "a stationary spin bike"],
    "rowing_machine": ["a photo of an indoor rowing machine",
                       "a rowing ergometer with a flywheel and sliding seat"],
    "elliptical": ["a photo of an elliptical cross trainer in a gym",
                   "an elliptical machine with moving arm handles and foot pedals"],
    "stair_climber": ["a photo of a stair climber machine in a gym",
                      "a stairmaster with rotating steps"],
    # Not a machine. A zero-shot model always picks something; without this class a selfie was
    # read as a captain's chair at 74%. When one of these wins, the app says it found no
    # machine instead of teaching the wrong exercise.
    "__none__": ["a photo of a person", "a selfie of a man standing in a room",
                 "a photo of an empty room", "a photo of a wall", "a photo of a street",
                 "a photo of food", "a photo of a person holding a phone"],
    # Not a machine. A zero-shot model always picks something; without this class a selfie was
    # read as a captain's chair at 74%. When it wins, the app says it found no machine instead
    # of teaching the wrong exercise.
    "__none__": ["a photo of a person", "a selfie of a man standing in a room",
                 "a photo of an empty room", "a photo of a wall", "a photo of a street",
                 "a photo of food", "a photo of a person holding a phone"],
}
